In [2]:
print("hello")

hello

In [6]:
#python as a calculator
print(2+2) #plus
print(2-2)
print(2/2)
print(2*2)

4
0
1.0
4

In [7]:
# x = 2
# 3 + x = 5

#variable declaration
mystring = "I am a string"
print(mystring)

#data type = string (essentially a word)
#Strings are categorised by ""

I am a string

In [11]:
print(int("2") + 2)
print("2" + str(2))

4
22

In [12]:
#string - you can concatanate
#concantenate - joing 2 strings together

partone = "Part" #variable declaration
parttwo = "2"

print(partone + parttwo)

Part2

In [15]:
#data structures - collection of values
#list - characterised by its []

mylist = ["1 ROOM", "2 ROOM", "3 ROOM", "4 ROOM", "5 ROOM"] #this list is a collection of 5 strings

print(mylist[1]) #index - list are queried by their indexes
#lists have zero-based indexes
print(mylist[0])

#pull out 4-ROOM
print(mylist[3])

2 ROOM
1 ROOM
4 ROOM

In [17]:
#dictionary - characterised by {}
#dictionares have key:value pairs

mydictionary = {"floor_area_sqm":34, "resale_price":300000} #mydictionary have 2 key:value pairs
print(mydictionary["floor_area_sqm"])

#pull out resale_price
print(mydictionary["resale_price"])

34
300000

In [21]:
#Dictionaries in list
mytable = [
    {"town":"BEDOK", "flat_type":"3 ROOM", "resale_price":300000},
    {"town":"Choa Chu Kang", "flat_type":"4 ROOM", "resale_price":500000},
    {"town":"Yishun", "flat_type":"5 ROOM", "resale_price":550000}
]

#mytable is a dictionaries in list
#mytable is a collection of 3 dictionaries
#each dictionary has 3 key:value pairs

print(mytable[0])
print(mytable[0]["flat_type"])

#pull out $550k from mytable
print(mytable[2]["resale_price"])

{'town': 'BEDOK', 'flat_type': '3 ROOM', 'resale_price': 300000}
3 ROOM
550000